version: "3"

services:
  app:
    build: .
    entrypoint: ./entrypoint.sh
    container_name: spring_api
    ports:
      - "8080:8080"
    volumes:
      - .:/home/usr/app
    working_dir: "/home/usr/app"
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: spring_api-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres