name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    environment: java-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./*"
          target: "/home/ubuntu/api_java"
      - name: Deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd api_java
            chmod +x ./entrypoint.sh
            sudo docker-compose down
            sudo docker-compose up
